name: Log Time Job

on:
  schedule:
  - cron: "*/5 * * * *" # Runs every 5 minutes
  
jobs:
  log_time:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run logging script
        run: |
          chmod +x log_time.sh
          ./log_time.sh

      - name: Commit and push changesa
        run: |
          git config --global user.VinceCampos "github-actions"
          git config --global user.campos.vince0119@gmail.com "github-actions@github.com"
          git add log.txt
          git commit -m "Update log file with new timestamp" || echo "No changes to commit"
          git push
